#!/bin/bash

# Get the Python file name from the environment variable
py_file="$PYFILE"

# Check if the PYFILE environment variable is set
if [ -z "$py_file" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

# Check if the specified Python file exists
if [ ! -f "$py_file" ]; then
    echo "Error: Python file '$py_file' not found."
    exit 1
fi

# Run the Python script
python3 "$py_file"

